steps:
  - label: ":rabbit2: Run benchmarks with CodSpeed"
    key: benchmarks
    command: |
      curl --proto '=https' --tlsv1.2 -LsSf https://github.com/CodSpeedHQ/runner/releases/download/v2.0.1-beta.1/codspeed-runner-installer.sh | bash;
      curl -fsSL https://get.pnpm.io/install.sh | bash -;
      source /root/.bashrc;
      pnpm env use --global 18;
      codspeed-runner --token=$CODSPEED_TOKEN --upload-url=$CODSPEED_UPLOAD_URL -- pnpm vitest bench;
