steps:
  - label: ":rabbit2: Run benchmarks with CodSpeed"
    key: benchmarks
    command: |
      curl --proto '=https' --tlsv1.2 -LsSf https://github.com/CodSpeedHQ/runner/releases/download/v2.0.1-beta.1/codspeed-runner-installer.sh | bash;
      source "$HOME/.cargo/env";
      curl -fsSL https://get.pnpm.io/install.sh | bash -;
      # source "$HOME/.bashrc";
      # pnpm env use --global 18;
      /root/.local/share/pnpm/pnpm setup;
      /root/.local/share/pnpm/pnpm i -g pnpm;
      pnpm env use --global 18;
      codspeed-runner --token=$CODSPEED_TOKEN --upload-url=$CODSPEED_UPLOAD_URL -- pnpm vitest bench;
