steps:
  - label: ":rabbit2: Run benchmarks with CodSpeed"
    key: benchmarks
    command: |
      set -x;
      curl --proto '=https' --tlsv1.2 -LsSf https://github.com/CodSpeedHQ/runner/releases/download/v2.0.1-beta.1/codspeed-runner-installer.sh | bash;
      source "$HOME/.cargo/env";
      apt install unzip -y;
      curl -fsSL https://fnm.vercel.app/install | bash;
      cat "$HOME/.bashrc";
      sed -e '/[ -z "$PS1" ] && return/s/^/#/g' -i /root/.bashrc
      cat "$HOME/.bashrc";
      source "$HOME/.bashrc";
      fnm install;
      corepack enable;
      codspeed-runner --token=$CODSPEED_TOKEN --upload-url=$CODSPEED_UPLOAD_URL -- /root/.local/share/pnpm/pnpm vitest bench;
    env:
      SHELL: /bin/bash
